### PR TITLE
Add originals for knockoutjs, dynamics crm, visual studio and MV*

### PR DESCRIPTION
**Pull request by ehorodyski**
Added originals I created for my site. None have variants as I saved them after completion and unfortunately I don't have any accompanying icons for MVC, MVP or MVVM. 

Not sure if you'll accept the Visual Studio one -- it's a tool rather than a language or framework, but I use it for Microsoft techs that have awful -- or no -- logos.

### CODE REVIEW

**Comment by ehorodyski** [comment]
Added originals I created for my site. None have variants as I saved them after completion and unfortunately I don't have any accompanying icons for MVC, MVP or MVVM.

Not sure if you'll accept the Visual Studio one -- it's a tool rather than a language or framework, but I use it for Microsoft techs that have awful -- or no -- logos.

*Edit*: Added a generic API icon to be used for Web Services, RESTful APIs, etc.

**Comment by konpa** [comment]
Thanks :) I'll have a look at your pull request as soon as possible!

**Comment by ehorodyski** [comment]
Awesome thank you! 
I dabble in graphic design but programming is my career. A lot of those I took and converted from logos so I'm hoping at the very least you (or the community) could clean them up and provide more variants. I'd do more but I'm a serious newbie to creating structured SVG files to be used in fonts. 

But I figured contributing *something* is better than nothing!

**Comment by oligibson** [comment]
@ehorodyski Closing this pull request because the repository it was created from no longer exists, so cannot be pulled into this repo. 

The Visual Studio Icon is now present in the codebase for the next release. If you want to add the others feel free to open another pull request or request them in issue #11

**Pull request closed without merging**
