### PR TITLE
Feature/transpilers

### PR DESCRIPTION
**Pull request by oligibson**

### CODE REVIEW

**Comment by konpa** [comment]
Hi @oligibson, I just saw that you add 2 pull requests with many icons added. Why did you close this one? I'm looking for someone to help me on this project, would you be interested?

**Comment by oligibson** [comment]
@konpa yes would be happy to help, I'm using Devicon for a project I'm working on and am adding icons as I need them. I have a couple of branches on my fork which could be merged into the main project. 

I'll open some pull requests for you to take a look at. I closed this one as I had some issues in the branch, I can reopen now.

**Comment by konpa** [comment]
Thanks a lot @oligibson !! I'll have a look at your pull requests as soon as possible and let you know. In the meantime, if you have any suggestions about the Devicon project or website, feel free to [share it with me](mailto:julien.monty@gmail.com) :)

**Comment by oligibson** [comment]
@konpa have you had a chance to look at any of those pull requests yet, I think it would be particularly beneficial to look to move the library to LESS or SASS or both, it will give developers an using these pre-processors easier inclusion, while keeping CSS available.

**Comment by konpa** [comment]
@oligibson I had a quick look at your pull requests today and will try to do a full review of all them today or in the coming days. Quick question in the meantime: how did you regenerate the font files after adding your icons? Thanks again for you contribution to the devicon project 👍

**Comment by oligibson** [comment]
@konpa I used icomoon - https://icomoon.io/

**Comment by konpa** [comment]
@oligibson OK, nice. I'm going to look for a way to automate this part, probably using gulp with a plugin like [gulp-iconfont](https://github.com/nfroidure/gulp-iconfont).

**Comment by oligibson** [comment]
@konpa that would be good and save a lot of time, could also look to automate the adding to the css/less files

**Pull request closed without merging**
