### PR TITLE
added couchdb icons and .sketch master file

### PR DESCRIPTION
**Pull request by Chippd**
Added couchdb icons. 

I used sketch. I included the master file but don't know how to reliably convert it to an .eps file as per the contributing guidelines.

@oligibson not sure how to use icomoon to update the font files, any help is appreciated. 

thank you

### CODE REVIEW

**Comment by oligibson** [comment]
@Chippd thanks for the contribution, I've converted the files to eps and added couchdb to the fonts, will be in the next release.

**Comment by Chippd** [comment]
@oligibson awesome thanks. 

Is that an ok workflow? Would like to contribute more. Let me know if there's anything I can do on my end to make it easier. Any links to a description on how to add to the fonts perhaps?

Thanks

**Comment by oligibson** [comment]
@Chippd it would be great if you could contribute more, there are so many icons requested and right now not much help in getting them added. I will put together a doc to better explain the contribution process and generating fonts soon. In the meantime check out [contributing.md](https://github.com/konpa/devicon/blob/master/CONTRIBUTING.md) it explains the naming convention and file types. 

For the icon to be added to the font we need a plain or line version as well as an original, you can see the changes I made to your commit here - [1e64939](https://github.com/konpa/devicon/commit/1e6493976df43ae5130c9df71057c5755cc52856) - that will show you what I did to add to the font, but I will write this up properly soon.

Thanks for your help so far, if in doubt contribute just the .svg files as you did here and I will update the font 👍

**Comment by Chippd** [comment]
@oligibson perfect, I was thinking of adding something to contributing.md myself (like some examples), as it took me a few reads to figure it out. I'll be adding more logos in the future, I'll need them for a project.

I'll take a look at your commit and try make the next PR easier. 

Cheers

**Pull request merged**
