### PR TITLE
Add various new platforms and languages (elixir, phoenix, arduino, minix, raspberry pi)

### PR DESCRIPTION
**Pull request by Kartstig**
- Fixes https://github.com/konpa/devicon/issues/100
- Fixes https://github.com/konpa/devicon/issues/101
- Relates to https://github.com/konpa/devicon/issues/83
- Fixes https://github.com/konpa/devicon/issues/33 ?

### CODE REVIEW

**Comment by amacado** [comment]
possible duplicate of #75 (phoenix) and #108 (arduino, pi)

**Comment by Berkmann18** [comment]
@amacado #108 was posted after this one, but yeah it indeed seems to be a duplicate of #75.

**Comment by amacado** [comment]
@Berkmann18 you're right. Anyway, I'm thinking about to propose a "one pull/issue" per icon rule as @iamclaytonray mentioned this will hopefully result in a cleaner state and structure. I'm working on a concept (CONTRIBUTE.md)..

**Comment by Kartstig** [comment]
Closing in favor of #216 #217 #218 #221

**Pull request closed without merging**
